const products = [
  {
    _id: "1",
    name: "Airpods",
    image: "/images/airpods.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis quam velit labore vel, soluta sequi autem nisi blanditiis quasi ut",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Airpods",
    image: "/images/airpods.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis quam velit labore vel, soluta sequi autem nisi blanditiis quasi ut",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "3",
    name: "Airpods",
    image: "/images/airpods.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis quam velit labore vel, soluta sequi autem nisi blanditiis quasi ut",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "Airpods",
    image: "/images/airpods.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis quam velit labore vel, soluta sequi autem nisi blanditiis quasi ut",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "Airpods",
    image: "/images/airpods.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis quam velit labore vel, soluta sequi autem nisi blanditiis quasi ut",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "6",
    name: "Airpods",
    image: "/images/airpods.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis quam velit labore vel, soluta sequi autem nisi blanditiis quasi ut",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "7",
    name: "Airpods",
    image: "/images/airpods.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis quam velit labore vel, soluta sequi autem nisi blanditiis quasi ut",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "8",
    name: "Airpods",
    image: "/images/airpods.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis quam velit labore vel, soluta sequi autem nisi blanditiis quasi ut",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "9",
    name: "Airpods",
    image: "/images/airpods.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis quam velit labore vel, soluta sequi autem nisi blanditiis quasi ut",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "10",
    name: "Airpods",
    image: "/images/airpods.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis quam velit labore vel, soluta sequi autem nisi blanditiis quasi ut",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
];

export default products;
